### ISSUE TITLE
Feature Request !!

### ISSUE THREAD

**Issue by bolavefasfas** [junedkh/jmdkh-mltb#10]
1. Mirror logs & Leech logs in 2 separate channels
**SS attached Below**  
- Mirror Logs 
![image](https://user-images.githubusercontent.com/82230241/192021467-52b31ca1-6fe3-49cb-9def-78e1772847b3.png)
- Leech Logs 
![image](https://user-images.githubusercontent.com/82230241/192021935-4b7f3b74-2d20-47a4-84a2-5ceca16ff155.png)

2. Source link button and copy of source link in 1 separate channel or the main grp itself is fine where the bot is running as members delete the source link its very hard to track abusers (IMP)

**SS attached Below**  

![image](https://user-images.githubusercontent.com/82230241/192022988-b13eac2a-502c-4277-ab7c-52d45694499b.png)
![image](https://user-images.githubusercontent.com/82230241/192024025-1d8608f4-9022-49b4-a694-aa4ee82f9fb8.png)

- Logs in separate channel 

![image](https://user-images.githubusercontent.com/82230241/192024853-ff4373fb-536d-40a0-b05a-8ab13117cfa9.png)

3. Sending Leeched files and Mirror links in user's PM (optional Not urgent)

4. Vue torrent for web ui 
`https://github.com/WDaan/VueTorrent`
5. Complete list of commands 
6. Custom docker image not the anas one 
7. **If torrents are added in webui from vpsip:8090 then they dont get uploaded to gdrive can you add that feature like even if we add torrents from web ui then torrents will get uploaded to TD/SD/Gdrive ? (IMP)**

- Can you tell which ones are you going to work on ?? ex 2 , 7 like this 
- Which one are you will be working on later 
- Which one you are absolutely not going to work on

**Comment by junedkh** [comment]
7. Skip
6. Never
5. Explain
4. Skip
3. Useless (you can authorise member who want mirror/leech in pm)
2. Okay.
1. It's there SECRET_LOG (I'll write in readme)

**Comment by bolavefasfas** [comment]
Bro how to use settings from bot to change vars whats the command ? other than usettings
