### ISSUE TITLE
Unable to split file in leech with direct link

### ISSUE THREAD

**Issue by githubprogit** [junedkh/jmdkh-mltb#11]
![unable-to-split](https://user-images.githubusercontent.com/83770392/192140399-993e4d77-d0a2-45fc-84f4-4e52c30ec6b9.png)

**Comment by junedkh** [comment]
Share the link

**Comment by githubprogit** [comment]
1) ffmpeg split only magnet/torrent video after /leech command but it does not split a direct link other then magnet/torrent video.

2) Only /leech command having issues more than 2 Gb file but /zipleech and other like command work properly.

**Comment by junedkh** [comment]
Share the particular link

**Comment by githubprogit** [comment]
what the link

**Comment by githubprogit** [comment]
> Share the particular link

What the link

**Comment by junedkh** [comment]
You are hiding.
Maybe problem in video file

**Comment by junedkh** [comment]
Zipleech work coz it's use 7z
Video file split using ffmpeg.
If you can share link i can't find proper solution.
I have tested many link but this error not appear.
