### ISSUE TITLE
Need feature

### ISSUE THREAD

**Issue by Captainsteve1** [junedkh/jmdkh-mltb#16]
Limited tasks at a time 
Pls add in config

**Comment by bolavefasfas** [comment]
Elaborate

**Comment by junedkh** [comment]
Explain more..

**Comment by Captainsteve1** [comment]
Eg: 
2 tasks at a time

**Comment by junedkh** [comment]
You mean for each user ?

**Comment by Captainsteve1** [comment]
Yes
And bot can handle 2tasks at a time

**Comment by bolavefasfas** [comment]
- Do you mean 1 user can only add 2 maximum tasks like that ?
- or in total the no matter the number of users the number of tasks wont exceed 2 like that ?
- and 2 is what we can set in config ?

**Comment by Captainsteve1** [comment]
Yes, ACTIVE_TASK_LIMIT: To limit the Total task for the bot, unrestricted for owner and sudo. use the integer
°USER_TASKS_LIMIT: Limit the task for every users of group, unrestricted for owner and sudo. use the integer

This 2 needed

**Comment by bolavefasfas** [comment]
Got it nice one useful for running groups

**Comment by bolavefasfas** [comment]
How about 1 more var bot will work for everyone on tg with 2 tasks per day and which are size limited lets say 2 gb 
and for more they have to pay to get upgraded plan 😁

**Comment by junedkh** [comment]
@Captainsteve1 are you using bot for group?

**Comment by junedkh** [comment]
Okay fine I'll add that feature

**Comment by Captainsteve1** [comment]
Why files not deleting in vps after completion of tasks

**Comment by junedkh** [comment]
Added that in version 2.7.2
