### ISSUE TITLE
Gdtot Clone

### ISSUE THREAD

**Issue by pachax001** [junedkh/jmdkh-mltb#20]
When cloning gdtot files getting this error
ERROR: Try in your browser, mostly file not found or user limit exceeded!
But when I try with a different bot the file get cloned. The repo I am using for the second bot is https://github.com/weebzone/WZML.

**Comment by bolavefasfas** [comment]
Yes crosschecked with multiple links facing same issue 
![image](https://user-images.githubusercontent.com/82230241/204320759-1c9bc777-d207-4cb0-9989-5f11dbecb5a7.png)

**Comment by junedkh** [comment]
We Will remove sharer support.

**Comment by bolavefasfas** [comment]
> We Will remove sharer support.

Bro DOnt do that just the url is updated
