### ISSUE TITLE
/dl cmd

### ISSUE THREAD

**Issue by theseeker99** [junedkh/jmdkh-mltb#21]
/dl cmd not working

**Comment by junedkh** [comment]
See [This](https://github.com/junedkh/jmdkh-mltb#bot-commands-to-be-set-in-botfather)

**Comment by theseekerofficial** [comment]
> See [This](https://github.com/junedkh/jmdkh-mltb#bot-commands-to-be-set-in-botfather)

I saw /dl cmd used to start mirror/leech tasks in a group. but after I deploy bot it's not working
