### ISSUE TITLE
Add Enable/Disable mirror/leech for mega. 

### ISSUE THREAD

**Issue by jbook1** [junedkh/jmdkh-mltb#28]
Could u add a new var to Enable/Disable mirror/leech from mega, members still try to mirror mega inspite for telling not to.. Or readd below two vars. 

Before there were two vars for mega BLOCK_MEGA_FOLDER & BLOCK_MEGA_LINKS, setting both to true used to block mega.

**Comment by hitesh920** [comment]
DISABLE_MEGA = ""

is what you needed

**Comment by junedkh** [comment]
Simply add limits for it bro
