### ISSUE TITLE
LOG_Chat not working for me

### ISSUE THREAD

**Issue by jbook1** [junedkh/jmdkh-mltb#29]
Filled LOG_CHAT with channel ID did not work.

Tried with **-100123456789** & **123456789** & **100123456789** still didn't get any logs. (**which one is correct?**)

Already added bot in that channel as admin.

**Below are the logs: (nothing wrong with the logs)**

jmdkh-mltb | 2022-12-20 08:23:45,230 - bot - INFO - onDownloadStarted: 100MB.bin - Gid: 97151c1120a17087
jmdkh-mltb | 2022-12-20 08:23:45,231 - bot - INFO - Aria2Download started: 97151c1120a17087
jmdkh-mltb | 2022-12-20 08:23:49,246 - bot - INFO - Checking File/Folder if already in Drive...
jmdkh-mltb | 2022-12-20 08:23:49,247 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 53.json service account
jmdkh-mltb | 2022-12-20 08:24:05,721 - bot - INFO - onDownloadComplete: 100MB.bin - Gid: 97151c1120a17087
jmdkh-mltb | 2022-12-20 08:24:05,728 - bot - INFO - Download completed: 100MB.bin
jmdkh-mltb | 2022-12-20 08:24:05,728 - bot - INFO - Upload Name: 100MB.bin
jmdkh-mltb | 2022-12-20 08:24:05,729 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 43.json service account
jmdkh-mltb | 2022-12-20 08:24:05,994 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploading File: /usr/src/app/downloads/3723/100MB.bin
jmdkh-mltb | 2022-12-20 08:24:09,490 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploaded To G-Drive: /usr/src/app/downloads/3723/100MB.bin
jmdkh-mltb | 2022-12-20 08:24:09,490 - bot - INFO - Done Uploading 100MB.bin
jmdkh-mltb | 2022-12-20 08:24:09,757 - bot - INFO - Cleaning Download: /usr/src/app/downloads/3723

**Am I missing something ?**

**Comment by jbook1** [comment]
OK.. it was not working in Bot PM but working with Mirror Group...

Just one query in readme it is mentioned that "**Four buttons are already added, Drive Link, Index Link, Log and View Link**"
 But i am not getting Log link (Log channel is already public)

**Comment by junedkh** [comment]
I'll edit readme file

**Comment by jbook1** [comment]
Exactly for what..
1. That LOG_CHAT works only with supergroup and not in Bot PM.
2. That we have to set mirror/clone log link button manually in buttons.txt & it won't appear automatically.
