### ISSUE TITLE
dude?

### ISSUE THREAD

**Issue by Nobody370** [junedkh/jmdkh-mltb#3]
How to change this options defaults to telegram and qbittorrent 
![IMG_20220903_024605](https://user-images.githubusercontent.com/88897873/188259463-0cff1623-ffc3-4469-9019-24fb3cd71c2b.jpg)

**Comment by junedkh** [comment]
can't but i will add all mirror related commons in future

**Comment by junedkh** [comment]
@Nobody370  I added that all commands
