### ISSUE TITLE
It's possible to add mirror to gofile?

### ISSUE THREAD

**Issue by ED8ET** [junedkh/jmdkh-mltb#30]
Hello Sir Google Drive TD Not Working anymore for new user.could u please add mirror to gofile I was searching recently I found but repo is dead not working.may I request this feature,here the repo is 
https://github.com/8figalltimepro/MOD-OF-MIRROR-BOT-BY-8

**Comment by junedkh** [comment]
Okay.
What's download speed from gofile?

**Comment by ED8ET** [comment]
Download almost good I have using my wifi 12MBps Download speed will go like 2-3mbps... but sadly upload speed little bit slow .

**Comment by junedkh** [comment]
Also it's not unlimited upload I think.
