### ISSUE TITLE
[feature request] ADD manually entering Multi Category ID in /mirror cmd

### ISSUE THREAD

**Issue by erickyun** [junedkh/jmdkh-mltb#32]
Hi,

İt would be nice if we could manually enter `categoryName` when using /mirror cmd.

Example:
We have setup `categories.txt` beforehand and execute a cmd like this
 `/mirror URL GdriveID:Movies`
But if no `GdriveID:` is specified in cmd it will download to default `GDRIVE_ID` from config.env.
Also something like `/mirror gd URL` to choose from `categories.txt` where to upload. 

İt would also be nice if could do this for `/rsssub` command.
Example:
`/rsssub Name RSSLİNK GdriveID:Movies`

Hope you will consider adding this in your TODO list sir?
Also I thank very much for your great work. :) 👍

**Comment by Master-Mind-007** [comment]
bro how to add gdtot in this repo ?
i tried by myself but it didn't worked

**Comment by junedkh** [comment]
I have added something what you explained try it but it will not enough for rss but will do something soon

**Comment by erickyun** [comment]
> I have added something what you explained try it but it will not enough for rss but will do something soon

Thank you very much sir. I will test it ASAP.
Can't wait for rss option. :)
