### ISSUE TITLE
Having issue while deploying 

### ISSUE THREAD

**Issue by mukto222** [junedkh/jmdkh-mltb#37]
![Screenshot_20230202-071419_Termius](https://user-images.githubusercontent.com/116914054/216239934-8c518511-d289-4da3-a3d3-5c9c16c40cea.jpg)

I wanted to deploy this on azure but facing problem please tell me what to do..

**Comment by junedkh** [comment]
you edit something wrong brother check requirements.txt

**Comment by junedkh** [comment]
this is not my repo
