### ISSUE TITLE
[BUG] Aria2 select inactive torrent file (/mirror s | /zipmirror s)

### ISSUE THREAD

**Issue by Namlee123** [junedkh/jmdkh-mltb#45]
Hello Bro!
I tried using the "/Mirror s" command to select the torrent file, but it doesn't pause, doesn't show the selection.
It directly executes the download command in the BOT Status.
Hope you can fix this in the future.

**Comment by junedkh** [comment]
do you add base url??
[READ](https://github.com/junedkh/jmdkh-mltb#qbittorrentaria2c)

**Comment by Namlee123** [comment]
> 

Yes, of course.
if using "/qm s" it works properly.
I re-ran your old repo (several months ago) it still works with "/mirror s".
But since you updated add:
(async, await) in module (bot/helper/mirror_utils/download_utils/aria2_download.py)
It encountered this error.
But I'm not sure if it's caused by (async, await) or not!
Yesterday, I tried the command "/miror s" in your Jmdkh group. Your vps BOT still has this error.

**Comment by junedkh** [comment]
fixed
