### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bolavefasfas** [junedkh/jmdkh-mltb#5]
- Can you add option to select Team Drive / folder in that drive before uploading

- Rclone encrypted remote upload instead of using credentials in addition to select which remote to upload like ex 

1. Animation: (rclone remote for gdrive ex)
2. Edu : (rclone remote dropbox)
3. Encrypted Movies : (Rclone remote)
so before uploading it should ask which remote to upload using qbit or aira or mega ..

Like this 

![image](https://user-images.githubusercontent.com/82230241/188279639-5cff0ca5-3a7b-4232-8299-dd6e3803acd2.png)

It would be amazing if could add these 

This would be like best repo 

[sample](https://graph.org/file/84708c84e2dfb73da052e.mp4)

If you could add these features

**Comment by Jarvis991** [comment]
Forwarded the req to Anasty too >> [link](https://github.com/anasty17/mirror-leech-telegram-bot/issues/1039#issuecomment-1236476239)

**Comment by junedkh** [comment]
I am working on it. Will release it soon.

**Comment by bolavefasfas** [comment]
> I am working on it. Will release it soon.

Eta ??

Approx

**Comment by junedkh** [comment]
Maybe after a month

**Comment by Tysonmovierulz** [comment]
Sir when adding this in Anas Sirs Repo...

**Comment by bolavefasfas** [comment]
Any update on "https://graph.org/file/84708c84e2dfb73da052e.mp4"
This ???
