### ISSUE TITLE
Please make all files editable.

### ISSUE THREAD

**Issue by iron-heart-x** [junedkh/jmdkh-mltb#6]
please make all file readable. 
please don't use encryption.
please
please
please

**Comment by junedkh** [comment]
are you using for personal?

**Comment by iron-heart-x** [comment]
> are you using for personal?

Yes, I am using for personal use and I am python learner.
please make all file readable
please

**Comment by junedkh** [comment]
Then use official repo brother.
This repo is designed for big groups. 🙏
