### ISSUE TITLE
[Feature Request] Particular User ID Blacklist Feature

### ISSUE THREAD

**Issue by tejas101k** [junedkh/jmdkh-mltb#64]
While authorizing a group chat [-100xxxxxx] meaning that giving a green flag to every group member present there for utilising the bot. But in a normal off topic/chat group consisting naturally of 20-25 members there are like 4-5 members which i don't want them using the bot. A simple scenario where i don't want to stop them being member of the group chat (by banning or kicking them) but just want to blacklist the particular user id's from using the bot. Like if the user id is in "BLACKLISTED_CHATS" config the bot won't be replying to particular blacklisted user in that group.

**Comment by Charsi-Tejas** [comment]
Just added it with a simple python workaround than i thought, in authorize module.
I will maybe later contribute with a pr after testing it.
